version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly         # 毎週実行
      day: monday              # 月曜日
      time: "15:00"            # 15:00
      timezone: Asia/Tokyo
    open-pull-requests-limit: 1  # PR上限を1に制限
    groups:
      bundler-updates:          # すべてのGem更新を1つにまとめる
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "15:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 1
    groups:
      actions-updates:
        patterns:
          - "*"
